
package frame;

import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author guibo
 */
public class DialogBossAlarm extends javax.swing.JDialog {

    /**
     * Creates new form DialogBossAlarm
     * @param parent
     * @param modal
     */
    public DialogBossAlarm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxBoss = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        comboBoxBoss1 = new javax.swing.JComboBox<>();
        comboBoxBoss2 = new javax.swing.JComboBox<>();
        comboBoxBoss3 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        labelClock = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BOSS ALARM");

        comboBoxBoss.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Abyssador", "Ahau", "Amenef The Burning", "Anomaly", "Black Vixen", "Bloodback", "Brain Head", "Brokul", "Chagorz", "Count Vlarkorth", "Darkfang", "Deathstrike", "Dragon Pack", "Drume", "Duke Krule", "Earl Osam", "Ekatrix", "Eradicator", "Essence Of Malice", "Faceless Bane", "Ghulosh", "Gnomevil", "Gorzindel", "Goshnar's Cruelty", "Goshnar's Greed", "Goshnar's Hatred", "Goshnar's Malice", "Goshnar's Spite", "Grand Master Oberon", "Ichgahal", "Irgix The Flimsy", "Katex Blood Tongue", "King Zelos", "Kusuma", "Lady Tenebris", "Lloyd", "Lokathmor", "Lord Azaram", "Lord Retro", "Magma Bubble", "Mazoran", "Mazzinor", "Megasylvan Yselda", "Melting Frozen Horror", "Mitmah Vanguard", "Murcion", "Neferi The Spy", "Outburst", "Plagirath", "Ragiaz", "Ratmiral Blackwhiskers", "Ravenous Hunger", "Razzagorn", "Realityquake", "Rupture", "Scarlett Etzel", "Shadowpelt", "Sharpclaw", "Shulgrax", "Sir Baeloc", "Sir Nictros", "Sister Hetai", "Soul Of Dragonking Zyrtarch", "Srezz Yellow Eyes", "Tarbaz", "Tentugly", "Thaian", "The Blazing Rose", "The Brainstealer", "The Diamond Blossom", "The Dread Maiden", "The Enraged Thorn Knight", "The False God", "The Fear Feaster", "The Flaming Orchid", "The Lily Of Night", "The Mega Magmaoid", "The Monster", "The Moonlight Aster", "The Nightmare Beast", "The Pale Worm", "The Sandking", "The Scourge Of Oblivion", "The Souldespoiler", "The Source Of Corruption", "The Time Guardian", "The Unarmored Voidborn", "The Unwelcome", "The Winter Bloom", "Timira The Many-Headed", "Unaz The Mean", "Urmahlullu The Weakened", "Utua Stone Sting", "Vemiath", "Vok The Freakish", "Yirkas Blue Scales", "Zamulosh" }));

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboBoxBoss1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Abyssador", "Ahau", "Amenef The Burning", "Anomaly", "Black Vixen", "Bloodback", "Brain Head", "Brokul", "Chagorz", "Count Vlarkorth", "Darkfang", "Deathstrike", "Dragon Pack", "Drume", "Duke Krule", "Earl Osam", "Ekatrix", "Eradicator", "Essence Of Malice", "Faceless Bane", "Ghulosh", "Gnomevil", "Gorzindel", "Goshnar's Cruelty", "Goshnar's Greed", "Goshnar's Hatred", "Goshnar's Malice", "Goshnar's Spite", "Grand Master Oberon", "Ichgahal", "Irgix The Flimsy", "Katex Blood Tongue", "King Zelos", "Kusuma", "Lady Tenebris", "Lloyd", "Lokathmor", "Lord Azaram", "Lord Retro", "Magma Bubble", "Mazoran", "Mazzinor", "Megasylvan Yselda", "Melting Frozen Horror", "Mitmah Vanguard", "Murcion", "Neferi The Spy", "Outburst", "Plagirath", "Ragiaz", "Ratmiral Blackwhiskers", "Ravenous Hunger", "Razzagorn", "Realityquake", "Rupture", "Scarlett Etzel", "Shadowpelt", "Sharpclaw", "Shulgrax", "Sir Baeloc", "Sir Nictros", "Sister Hetai", "Soul Of Dragonking Zyrtarch", "Srezz Yellow Eyes", "Tarbaz", "Tentugly", "Thaian", "The Blazing Rose", "The Brainstealer", "The Diamond Blossom", "The Dread Maiden", "The Enraged Thorn Knight", "The False God", "The Fear Feaster", "The Flaming Orchid", "The Lily Of Night", "The Mega Magmaoid", "The Monster", "The Moonlight Aster", "The Nightmare Beast", "The Pale Worm", "The Sandking", "The Scourge Of Oblivion", "The Souldespoiler", "The Source Of Corruption", "The Time Guardian", "The Unarmored Voidborn", "The Unwelcome", "The Winter Bloom", "Timira The Many-Headed", "Unaz The Mean", "Urmahlullu The Weakened", "Utua Stone Sting", "Vemiath", "Vok The Freakish", "Yirkas Blue Scales", "Zamulosh" }));

        comboBoxBoss2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Abyssador", "Ahau", "Amenef The Burning", "Anomaly", "Black Vixen", "Bloodback", "Brain Head", "Brokul", "Chagorz", "Count Vlarkorth", "Darkfang", "Deathstrike", "Dragon Pack", "Drume", "Duke Krule", "Earl Osam", "Ekatrix", "Eradicator", "Essence Of Malice", "Faceless Bane", "Ghulosh", "Gnomevil", "Gorzindel", "Goshnar's Cruelty", "Goshnar's Greed", "Goshnar's Hatred", "Goshnar's Malice", "Goshnar's Spite", "Grand Master Oberon", "Ichgahal", "Irgix The Flimsy", "Katex Blood Tongue", "King Zelos", "Kusuma", "Lady Tenebris", "Lloyd", "Lokathmor", "Lord Azaram", "Lord Retro", "Magma Bubble", "Mazoran", "Mazzinor", "Megasylvan Yselda", "Melting Frozen Horror", "Mitmah Vanguard", "Murcion", "Neferi The Spy", "Outburst", "Plagirath", "Ragiaz", "Ratmiral Blackwhiskers", "Ravenous Hunger", "Razzagorn", "Realityquake", "Rupture", "Scarlett Etzel", "Shadowpelt", "Sharpclaw", "Shulgrax", "Sir Baeloc", "Sir Nictros", "Sister Hetai", "Soul Of Dragonking Zyrtarch", "Srezz Yellow Eyes", "Tarbaz", "Tentugly", "Thaian", "The Blazing Rose", "The Brainstealer", "The Diamond Blossom", "The Dread Maiden", "The Enraged Thorn Knight", "The False God", "The Fear Feaster", "The Flaming Orchid", "The Lily Of Night", "The Mega Magmaoid", "The Monster", "The Moonlight Aster", "The Nightmare Beast", "The Pale Worm", "The Sandking", "The Scourge Of Oblivion", "The Souldespoiler", "The Source Of Corruption", "The Time Guardian", "The Unarmored Voidborn", "The Unwelcome", "The Winter Bloom", "Timira The Many-Headed", "Unaz The Mean", "Urmahlullu The Weakened", "Utua Stone Sting", "Vemiath", "Vok The Freakish", "Yirkas Blue Scales", "Zamulosh" }));

        comboBoxBoss3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Abyssador", "Ahau", "Amenef The Burning", "Anomaly", "Black Vixen", "Bloodback", "Brain Head", "Brokul", "Chagorz", "Count Vlarkorth", "Darkfang", "Deathstrike", "Dragon Pack", "Drume", "Duke Krule", "Earl Osam", "Ekatrix", "Eradicator", "Essence Of Malice", "Faceless Bane", "Ghulosh", "Gnomevil", "Gorzindel", "Goshnar's Cruelty", "Goshnar's Greed", "Goshnar's Hatred", "Goshnar's Malice", "Goshnar's Spite", "Grand Master Oberon", "Ichgahal", "Irgix The Flimsy", "Katex Blood Tongue", "King Zelos", "Kusuma", "Lady Tenebris", "Lloyd", "Lokathmor", "Lord Azaram", "Lord Retro", "Magma Bubble", "Mazoran", "Mazzinor", "Megasylvan Yselda", "Melting Frozen Horror", "Mitmah Vanguard", "Murcion", "Neferi The Spy", "Outburst", "Plagirath", "Ragiaz", "Ratmiral Blackwhiskers", "Ravenous Hunger", "Razzagorn", "Realityquake", "Rupture", "Scarlett Etzel", "Shadowpelt", "Sharpclaw", "Shulgrax", "Sir Baeloc", "Sir Nictros", "Sister Hetai", "Soul Of Dragonking Zyrtarch", "Srezz Yellow Eyes", "Tarbaz", "Tentugly", "Thaian", "The Blazing Rose", "The Brainstealer", "The Diamond Blossom", "The Dread Maiden", "The Enraged Thorn Knight", "The False God", "The Fear Feaster", "The Flaming Orchid", "The Lily Of Night", "The Mega Magmaoid", "The Monster", "The Moonlight Aster", "The Nightmare Beast", "The Pale Worm", "The Sandking", "The Scourge Of Oblivion", "The Souldespoiler", "The Source Of Corruption", "The Time Guardian", "The Unarmored Voidborn", "The Unwelcome", "The Winter Bloom", "Timira The Many-Headed", "Unaz The Mean", "Urmahlullu The Weakened", "Utua Stone Sting", "Vemiath", "Vok The Freakish", "Yirkas Blue Scales", "Zamulosh" }));

        jLabel1.setText("SELECIONE OS BOSSES:");

        labelClock.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        labelClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClock.setToolTipText("");
        labelClock.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxBoss3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxBoss, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxBoss1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxBoss2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelClock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboBoxBoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxBoss1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelClock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxBoss2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxBoss3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    LocalTime time = LocalTime.now();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
    String horaFormatada = time.format(formatter);
    String[] vectHoras = horaFormatada.split(":");
    private int horas = Integer.parseInt(vectHoras[0]);
    private int minutos = Integer.parseInt(vectHoras[1]);
    private int segundos = Integer.parseInt(vectHoras[2]);

    public void iniciarRelogio() {
        Thread threadRelogio;
        threadRelogio = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    atualizarTempo();
                    labelClock.setText(obterHoraAtual());
                    if (labelClock.getText().equals("16:38:30")) {
                        String Selectboss1 = comboBoxBoss.getSelectedItem().toString().trim();
                        String Selectboss2 = comboBoxBoss1.getSelectedItem().toString().trim();
                        String Selectboss3 = comboBoxBoss2.getSelectedItem().toString().trim();
                        String Selectboss4 = comboBoxBoss3.getSelectedItem().toString().trim();
                        String boss = verificarBoss();
                        if (boss.contains(Selectboss1.toUpperCase()) || boss.contains(Selectboss2.toUpperCase()) || boss.contains(Selectboss3.toUpperCase()) || boss.contains(Selectboss4.toUpperCase())) {
                            try {
                                URI link = new URI("https://www.youtube.com/watch?v=dMSFqXGZ5TQ");
                                Desktop.getDesktop().browse(link);
                            } catch (URISyntaxException ex) {
                                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
                            } catch (IOException ex) {
                                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
                            }
                        }
                    }
                    try {
                        Thread.sleep(1000); // Aguarda 1 segundo
                    } catch (InterruptedException e) {
                    }
                }
            }

        });
        threadRelogio.start();

    }

    public void atualizarTempo() {
        segundos++;
        if (segundos == 60) {
            segundos = 0;
            minutos++;
            if (minutos == 60) {
                minutos = 0;
                horas++;
                if (horas == 24) {
                    horas = 0;
                }
            }
        }
    }
    
    public String obterHoraAtual() {
        return String.format("%02d:%02d:%02d", horas, minutos, segundos);
    }

    private String verificarBoss() {

        HttpClient client = HttpClient.newHttpClient();
        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create("https://dev.tibiadata.com/v4/boostablebosses"))
                .header("accept", "application/json")
                .build();

        try {
            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
            
            String jsonBoss = response.body();
            String boss = jsonBoss.substring(0,176).toUpperCase();
            return boss;
            
        } catch (IOException | InterruptedException e) {
        }
        String boss = "";
        return boss;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      iniciarRelogio();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogBossAlarm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogBossAlarm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogBossAlarm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogBossAlarm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogBossAlarm dialog = new DialogBossAlarm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxBoss;
    private javax.swing.JComboBox<String> comboBoxBoss1;
    private javax.swing.JComboBox<String> comboBoxBoss2;
    private javax.swing.JComboBox<String> comboBoxBoss3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelClock;
    // End of variables declaration//GEN-END:variables
}
